site_url : https://asalvadorc.github.io/BBDD_Tema2
site_name: BD - Bases de Dades
theme: 
  name: readthedocs
  logo: assets/logocaminas.png

extra_css:
  - css/extra.css 
nav:
  - Tema 2-Modelo Entidad-Relación:
    - Objectius i coneixements previs: BD-T02_Model_E-R/objectius_i_coneixements_previs.md
    - 1. Introducció: BD-T02_Model_E-R/1_introducci.md
    - 2. Exemple: BD-T02_Model_E-R/2_exemple.md
    - 3. Les Entitats del Model E/R: BD-T02_Model_E-R/3_les_entitats_del_model_er.md
    - Exercicis: BD-T02_Model_E-R/exercicis.md
    - 4. Les Relacions del Model E/R: BD-T02_Model_E-R/4_les_relacions_del_model_er.md
    - Exercicis: BD-T02_Model_E-R/exercicis0.md
    - 5. Relacions de grau major que dos: BD-T02_Model_E-R/5_relacions_de_grau_major_que_dos.md
    - 6. Model E/R Estès: BD-T02_Model_E-R/6_model_er_ests.md
    - 7. Restriccions externes: BD-T02_Model_E-R/7_restriccions_externes.md
    - Exercicis: BD-T02_Model_E-R/exercicis1.md
    - Informació addicional: BD-T02_Model_E-R/informaci_addicional.md
  